export const Calendar = [
  {date: 1, day: 'Sunday', weekday: false, month: 'December', year: 2024},
  {date: 2, day: 'Monday', weekday: true, month: 'December', year: 2024},
  {date: 3, day: 'Tuesday', weekday: true, month: 'December', year: 2024},
  {date: 4, day: 'Wednesday', weekday: true, month: 'December', year: 2024},
  {date: 5, day: 'Thursday', weekday: true, month: 'December', year: 2024},
  {date: 6, day: 'Friday', weekday: true, month: 'December', year: 2024},
  {date: 7, day: 'Saturday', weekday: false, month: 'December', year: 2024},
  {date: 8, day: 'Sunday', weekday: false, month: 'December', year: 2024},
  {date: 9, day: 'Monday', weekday: true, month: 'December', year: 2024},
  {date: 10, day: 'Tuesday', weekday: true, month: 'December', year: 2024},
  {date: 11, day: 'Wednesday', weekday: true, month: 'December', year: 2024},
  {date: 12, day: 'Thursday', weekday: true, month: 'December', year: 2024},
  {date: 13, day: 'Friday', weekday: true, month: 'December', year: 2024},
  {date: 14, day: 'Saturday', weekday: false, month: 'December', year: 2024},
  {date: 15, day: 'Sunday', weekday: false, month: 'December', year: 2024},
  {date: 16, day: 'Monday', weekday: true, month: 'December', year: 2024},
  {date: 17, day: 'Tuesday', weekday: true, month: 'December', year: 2024},
  {date: 18, day: 'Wednesday', weekday: true, month: 'December', year: 2024},
  {date: 19, day: 'Thursday', weekday: true, month: 'December', year: 2024},
  {date: 20, day: 'Friday', weekday: true, month: 'December', year: 2024},
  {date: 21, day: 'Saturday', weekday: false, month: 'December', year: 2024},
  {date: 22, day: 'Sunday', weekday: false, month: 'December', year: 2024},
  {date: 23, day: 'Monday', weekday: true, month: 'December', year: 2024},
  {date: 24, day: 'Tuesday', weekday: true, month: 'December', year: 2024},
  {
    date: 25,
    day: 'Wednesday',
    weekday: false,
    holiday: 'Christmas',
    month: 'December',
    year: 2024,
  },
  {date: 26, day: 'Thursday', weekday: true, month: 'December', year: 2024},
  {date: 27, day: 'Friday', weekday: true, month: 'December', year: 2024},
  {date: 28, day: 'Saturday', weekday: false, month: 'December', year: 2024},
  {date: 29, day: 'Sunday', weekday: false, month: 'December', year: 2024},
  {date: 30, day: 'Monday', weekday: true, month: 'December', year: 2024},
  {date: 31, day: 'Tuesday', weekday: true, month: 'December', year: 2024},
];
